# Netlify configuration for SPA routing and scroll-to-top
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Set custom headers if needed
#[[headers]]
#  for = "/index.html"
#  [headers.values]
#    X-Frame-Options = "DENY"
#    X-XSS-Protection = "1; mode=block"

# Note: For scroll-to-top on route change, handle in your React app (see below)
# Example (add to App.jsx or main layout):
# useEffect(() => { window.scrollTo(0, 0); }, [location.pathname]);
